# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover_picture', models.ImageField(default='book_picture/default-book.png', upload_to='book_picture/')),
                ('authors', models.ManyToManyField(to='userapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_status', models.CharField(blank=True, choices=[('A', 'American'), ('I', 'Indian'), ('P', 'Photocopy')], max_length=1, null=True)),
                ('condition', models.CharField(blank=True, choices=[('G', 'Good'), ('M', 'Medium'), ('B', 'Bad')], max_length=1, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=7, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(default='profile_picture/default-user.png', upload_to='profile_picture/')),
                ('role', models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('M', 'Moderator')], default='U', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='serial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
        migrations.AddField(
            model_name='currentholder',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
        migrations.AddField(
            model_name='currentholder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Product', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='serial',
            unique_together=set([('product', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('owner', 'book')]),
        ),
    ]
